spring:
  servlet:
    multipart:
      max-file-size: 4MB
  cloud:
    aws:
      region:
        static: eu-central-1
      dynamodb:
        endpoint: ${DYNAMO_DB_ENDPOINT}
aws:
  bucket-name: ${BUCKET_NAME}
  task-queue-sqs: ${TASK_QUEUE_SQS}
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
